name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        include:
          - KUBE_VERSION: v1.29.0
            GO_VERSION: 1.21
            PLATFORMS: linux/amd64
          - KUBE_VERSION: v1.30.0
            GO_VERSION: 1.22
            PLATFORMS: linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}},value=${{ matrix.KUBE_VERSION }},enable=${{ github.event_name != 'pull_request' }}
            type=semver,pattern={{version}}-{{sha}},value=${{ matrix.KUBE_VERSION }},enable=${{ github.event_name != 'pull_request' }}
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr,suffix=-{{sha}}
      - uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.PLATFORMS }}
          cache-from: type=gha,scope=kube-${{ matrix.KUBE_VERSION }}-go-${{ matrix.GO_VERSION }}
          cache-to: type=gha,mode=max,scope=kube-${{ matrix.KUBE_VERSION }}-go-${{ matrix.GO_VERSION }}
          pull: true
          push: true
          build-args: |
            GO_VERSION=${{ matrix.GO_VERSION }}
            KUBE_VERSION=${{ matrix.KUBE_VERSION }}
