name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        include:
          - KUBE_VERSION: v1.29.15
            GO_VERSION_KUBE: 1.21
            PLATFORMS: linux/amd64,linux/arm64
          - KUBE_VERSION: v1.30.14
            GO_VERSION_KUBE: 1.22
            PLATFORMS: linux/amd64,linux/arm64
          - KUBE_VERSION: v1.31.12
            GO_VERSION_KUBE: 1.22
            PLATFORMS: linux/amd64,linux/arm64
          - KUBE_VERSION: v1.32.8
            GO_VERSION_KUBE: 1.23
            PLATFORMS: linux/amd64,linux/arm64
          - KUBE_VERSION: v1.33.4
            GO_VERSION_KUBE: 1.24
            PLATFORMS: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.KUBE_VERSION }},prefix=v,enable=${{ github.event_name != 'pull_request' }}
            type=semver,pattern={{version}},value=${{ matrix.KUBE_VERSION }},prefix=v,suffix=-{{sha}},enable=${{ github.event_name != 'pull_request' }}
      - uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.PLATFORMS }}
          cache-from: type=gha,scope=kube-${{ matrix.KUBE_VERSION }}-go-${{ matrix.GO_VERSION }}
          cache-to: type=gha,mode=max,scope=kube-${{ matrix.KUBE_VERSION }}-go-${{ matrix.GO_VERSION }}
          pull: true
          push: true
          build-args: |
            GO_VERSION_KUBE=${{ matrix.GO_VERSION_KUBE }}
            KUBE_VERSION=${{ matrix.KUBE_VERSION }}
