name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        KUBE_VERSION: [v1.29.0, v1.30.0, v1.31.0]
        GO_VERSION: [1.21, 1.22]
        include:
          - KUBE_VERSION: v1.29.0
            GO_VERSION: 1.21
        # - KUBE_VERSION: v1.30.0
        #   GO_VERSION: 1.22
        # - KUBE_VERSION: v1.31.0
        #   GO_VERSION: 1.22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}},value=${{ matrix.KUBE_VERSION }},enable=${{ github.event_name != 'pull_request' }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          push: true
          arguments: |
            GO_VERSION=${{ matrix.GO_VERSION }}
            KUBE_VERSION=${{ matrix.KUBE_VERSION }}
